+---------------------+
| TestNumeroMagico     |
+---------------------+
|                     |
| test_numero_magico() |
+---------------------+
            |
            v
+---------------------+
|                     |
|    numero_magico     |
|    numero_usuario    |
|                     |
+---------------------+
            |
            v
            *
            |
            v
+---------------------+
|                     |
|     input()          |
|       *             |
|    numero_usuario    |
|       *=            |
|        *            |
|    numero_magico     |
|       *=            |
|                     |
+---------------------+
            |
            v
+---------------------+
|                     |
|       print()        |
|                     |
+---------------------+
